### ISSUE TITLE
Add more place types

### ISSUE THREAD

**Issue by angelk** [trackhub/website#165]
Add the following place types

- Restaurant
- Hotel
- Bike shop/service

**Comment by jakub231** [comment]
Hi, I would like to work on this issue. Can you give me more informations about that? Thanks

**Comment by angelk** [comment]
Hello,

thank you for the interest!

![type](https://user-images.githubusercontent.com/1329009/68242727-bb03eb00-0019-11ea-9bbf-7caa0a1a3463.png)

There should be a new place type.
Here are places that should be changed:

- https://github.com/trackhub/website/blob/master/src/Entity/Place.php#L23 add new contant
- https://github.com/trackhub/website/blob/master/src/Form/Type/Place.php#L39 add input option + translation
- Add DB migration https://github.com/trackhub/website/tree/master/script/migration/migrations 

You can read more about phinx migrations here - https://book.cakephp.org/3/en/phinx/migrations.html#creating-a-new-migration

Ping me if you have any issues/questions

**Comment by jakub231** [comment]
Why do you need add DB Migration?

**Comment by angelk** [comment]
Ah, I thought the type was `enum`. I was wrong. Migrations is not needed

**Comment by jakub231** [comment]
All right. Can you assign me on this issue?

**Comment by jakub231** [comment]
I installed project but I didnt know where set local database or run project. Please help me!

**Comment by angelk** [comment]
All you have to do is to run `bash run.sh`. It is described in the readme of the project.
This will create and run containers. Database will be created automatically.

**Comment by jakub231** [comment]
When I got this command docker exec -it -u www-data track_web_1 bash
got only Error: No such container: track_web_1 and when clicked on http://localhost/website/public/index.php/en I get 
![image](https://user-images.githubusercontent.com/56276291/68585163-b445ff80-0481-11ea-8f77-9fbaa53c7e9c.png)

**Comment by jakub231** [comment]
Please help me

**Comment by angelk** [comment]
I see that you are running windows.
We are not supporting Windows OS. The CI is not supporting windows, so we cant add tests for the windows OS.
I will see what can I do.

**Comment by angelk** [comment]
Here is how it may work
1) remove sql container `docker rm track_sql_1`
2) remove sql volume if exists, check `docker volume ls`
3) Edit docker-compose.yml
Remove
```
    volumes:
    - ./docker/var/sql:/var/lib/mysql
```

from the sql container configuration
Add port forwarding for web container
```
    ports:
      - "80:80"
```
The docker-compose.yml should be something like
```
version: "3"
services:
  web:
    restart: unless-stopped
    build: docker/web/dev
    volumes:
    - ./:/var/www
    environment:
    - WEB_UID=${WEB_UID}
    depends_on:
      - sql
    ports:
      - "80:80"
  sql:
    restart: unless-stopped
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_USER: gps
      MYSQL_PASSWORD: 1
      MYSQL_DATABASE: gps
```

Add the following line in hosts file - c:\windows\system32\drivers\etc\hosts
```
127.0.0.1 gps.test
```

Install https://git-scm.com/ , make sure to check "checkout as-is, commit as-is"!
Using git bash start the `run.sh` script.
Wait, wait a lot, like 15 minutes.
You should see `| AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using....`

Open http://gps.test/ 

If there are issues, please provide me with the output of run.sh
